/**
 * Firestore trigger — runs whenever a message is created in a service chat
 * (`servicios/{serviceId}/mensajes/{messageId}`).
 *
 * If the message text matches any of the contact-info / off-platform bypass
 * patterns, the write is redacted in place: the offending body is replaced
 * with a system notice explaining the block. The original text is stored on a
 * private `admin_flags` document for moderation review.
 *
 * System messages (`tipo === 'sistema'`) and image messages are exempt — they
 * are generated by our own code paths, not by users.
 */

import { onDocumentCreated } from 'firebase-functions/v2/firestore';
import { db, admin } from './lib/admin';
import { scan } from './lib/contact-info-filter';
import { sendPushToUser } from './lib/push';

export const onChatMessageCreated = onDocumentCreated(
  {
    document: 'servicios/{serviceId}/mensajes/{messageId}',
    region: 'us-central1',
  },
  async (event) => {
    const snap = event.data;
    if (!snap) return;
    const data = snap.data();

    const tipo = (data.tipo as string | undefined) ?? 'texto';
    const serviceId = event.params.serviceId as string;
    const messageId = event.params.messageId as string;

    // System messages skip the filter (they come from our own server) but we
    // still fan out lifecycle-event pushes below.
    if (tipo !== 'sistema') {
      const text = (data.mensaje as string | undefined) ?? '';
      const violation = tipo === 'imagen' ? null : scan(text);

      if (violation) {
        // Redact the message in place — same doc id, so client streams see
        // the block immediately without needing an extra listener.
        await snap.ref.set(
          {
            mensaje: `⚠️ Mensaje bloqueado: ${violation.message}`,
            tipo: 'sistema',
            metadata: {
              event: 'blocked_by_filter',
              reason: violation.reason,
              originalUserId: data.userId ?? null,
            },
          },
          { merge: true },
        );
        await db.collection('admin_flags').add({
          type: 'chat_contact_info_leak_attempt',
          serviceId,
          messageId,
          offenderUid: data.userId ?? null,
          offenderName: data.nombreUsuario ?? null,
          originalText: text,
          reason: violation.reason,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
        });
        // Do NOT push a notification for a blocked message.
        return;
      }
    }

    // ---- Push notification fan-out ----
    // Load the service so we know the two participants. Push to everyone
    // EXCEPT the sender (user messages → other party only; system events →
    // both parties since neither of them is the "sender").
    const serviceSnap = await db.collection('servicios').doc(serviceId).get();
    if (!serviceSnap.exists) return;
    const service = serviceSnap.data()!;
    const clienteId = service.clienteId as string | undefined;
    const tecnicoId = service.tecnicoId as string | undefined;
    const senderUid = data.userId as string | undefined;

    const recipients = [clienteId, tecnicoId].filter(
      (u): u is string => !!u && u !== senderUid,
    );
    if (recipients.length === 0) return;

    const title = tipo === 'sistema'
      ? 'ServiTec'
      : `Nuevo mensaje · ${data.nombreUsuario ?? 'ServiTec'}`;
    const bodyPreview = tipo === 'imagen'
      ? '📷 Foto'
      : (data.mensaje as string | undefined)?.slice(0, 120) ?? '';

    await Promise.all(
      recipients.map((uid) =>
        sendPushToUser(uid, {
          title,
          body: bodyPreview,
          data: {
            type: 'chat_message',
            serviceId,
            messageId,
          },
        }),
      ),
    );
  },
);
